version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/elixir:1.9.1
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout # check out the code in the project directory
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix coveralls
      - run: mix dialyzer
